services:
  - type: web
    name: gonzales-portfolio
    env: docker          
    region: singapore

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_URL
        value: https://gonzales-portfolio.onrender.com

      - key: APP_KEY     
        sync: false

      - key: DB_CONNECTION
        value: sqlite

      - key: DB_DATABASE
        value: /tmp/database.sqlite   